# This is an example configuration for the triggerhappy daemon (thd)
# please note that every file to be processed must end in ".conf"
#
# To view a list of supported event codes, use "thd --listevents" or
# "thd --dump /dev/input/event*"
#
# Format:
# <eventcode> <value> <command>
#
# values for key events are 1 (pressed), 0 (released) or 2 (held)
#
KEY_U		1	/sbin/uci commit sensors
# sensors enabled/disabled
KEY_F1		1	/sbin/uci set sensors.@circuitpython[0].disabled=0
KEY_F2		1	 /sbin/uci set sensors.@circuitpython[0].disabled=1
# charging state
KEY_PAGEUP	1	 /sbin/uci set sensors.@circuitpython[0].charging=1
KEY_PAGEDOWN	1	 /sbin/uci set sensors.@circuitpython[0].charging=0
# submit CPU Temp
KEY_C		1	/sbin/uci set sensors.@circuitpython[0].cputemp=$(cat /tmp/sensorvalue)
# submit Battery_Voltage
KEY_V		1	/sbin/uci set sensors.@circuitpython[0].voltage=$(cat /tmp/sensorvalue )
#
# BMP280 Values
#
KEY_T		1	/sbin/uci set sensors.@bmp280[0].temperature=$(cat /tmp/sensorvalue )
KEY_P		1	/sbin/uci set sensors.@bmp280[0].pressure=$(cat /tmp/sensorvalue )
# send sensor values and concat in /tmp/sensorvalue
KEY_1		1	echo -n "1" >>/tmp/sensorvalue
KEY_2		1	echo -n "2" >>/tmp/sensorvalue
KEY_3		1	echo -n "3" >>/tmp/sensorvalue
KEY_4		1	echo -n "4" >>/tmp/sensorvalue
KEY_5		1	echo -n "5" >>/tmp/sensorvalue
KEY_6		1	echo -n "6" >>/tmp/sensorvalue
KEY_7		1	echo -n "7" >>/tmp/sensorvalue
KEY_8		1	echo -n "8" >>/tmp/sensorvalue
KEY_9		1	echo -n "9" >>/tmp/sensorvalue
KEY_0		1	echo -n "0" >>/tmp/sensorvalue
# sensorvalues signs like . , -
KEY_DOT		1	echo -n "." >>/tmp/sensorvalue
KEY_COMMA	1	echo -n "," >>/tmp/sensorvalue
KEY_MINUS	1	echo -n "-" >>/tmp/sensorvalue
# clear sensorvalue variable
KEY_BACKSPACE	1	echo -n "" >/tmp/sensorvalue
